language: c++
sudo: required
dist: trusty

addons:
 apt:
   sources:
   - trusty
   - sourceline 'ppa:ppettina/gstreamer1.6.0+trusty'
   - sourceline 'deb http://repos.dc.baikal.ru/projects beryllium main'
   packages:
   - libdcmtk2-dev
   - libboost-dev
   - libmediainfo-dev
   - libssl-dev
   - libwrap0-dev
   - libgudev-1.0-dev
   - libgstreamer1.0-dev
   - libqtgstreamer-dev
   - libgstreamer-plugins-base1.0-dev
   - libqt5opengl5-dev
   - libqt5gstreamer-dev
   - libavc1394-dev
   - libraw1394-dev
   - libv4l-dev

script:
   - cp docs/* debian/
   - dpkg-buildpackage -I.git -I*.sh -rfakeroot

