language: c++
addons:
 apt:
   sources:
   - xenial
   packages:
   - libdcmtk2-dev
   - libboost-dev
   - libmediainfo-dev
   - libssl-dev
   - libwrap0-dev
   - libgudev-1.0-dev
   - libgstreamer1.0-dev
   - libqtgstreamer-dev
   - libgstreamer-plugins-base1.0-dev
   - libqt5opengl5-dev
   - libqt5gstreamer-dev
   - libavc1394-dev
   - libraw1394-dev
   - libv4l-dev
script:
   - cp docs/* debian/
   - dpkg-buildpackage -I.git -I*.sh -rfakeroot

